name: Deploy on Tag

on:
  push:
    tags:
      - 'vx.y.z'
    
jobs:
  deploy:
    name: Build
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build debug APK
        run: bash ./gradlew assembleRelease --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: app/build/outputs/apk/release*.apk

